---
- hosts: all
  become: true
  tasks:

    - name: Install Python3 and Pip3  
      package:
        name: "{{ item }} " 
        state: latest
      with_items:
        - python3
        - python3-pip
    
    - name: Set pip3 as the default python for Ubuntu
      command: "ln -sf /usr/bin/pip3 /usr/bin/pip"
      when: ansible_distribution == "Ubuntu"

    - name: Set pip3 as the default python for CentOS
      command: "ln -sf /usr/bin/pip3 /usr/bin/pip"
      when: ansible_distribution == "CentOS"

    - name: Set python3 as the default python for Ubuntu
      command: "ln -sf /usr/bin/python3 /usr/bin/python"
      when: ansible_distribution == "Ubuntu"

    - name: Set python3 as the default python for CentOS
      command: "ln -sf /usr/bin/python3 /usr/bin/python"
      when: ansible_distribution == "CentOS"

    - name: Install OpenJDK for Ubuntu
      apt:
        name: openjdk-11-jdk
        state: latest
        update_cache: yes
      when: ansible_distribution = "Ubuntu"

    - name: Install OpenJDK for CentOS
      dnf:
        name: openjdk-11-jdk
        state: latest
        update_cache: yes
      when: ansible_distribution = "CentOS"

     
    - name: Set Motd
      template:
        src: motd.j2
        dest: /etc/motd
      vars:
        custom_motd: "{{ motd_text | default('Ansible Managed node by ' ~ jai) }}"


